name: "`openMCP` Issue"
description: "Guided creation of a bug report for `openMCP`"
title: "<problem title> "
labels: ["kind/bug", "needs/tech-advice"]
body:
  - type: markdown
    attributes:
      value: "# Impact"
  - type: markdown
    attributes:
      value: |
        Please provide as much information as possible for this bug report, such as specifying any error messages you have seen, and/or
        describing in detail what exactly happened.
        By categorizing and prioritizing the issue appropriately, you can help us process this issue faster.
  - type: textarea
    id: similar-issues
    attributes:
      label: "Is the same problem already mentioned in other bug reports ?"
      description: In case other users have reported similar issues already, please post the issue links here.
      placeholder: "Links to other issues reporting a similar problem."
    validations:
      required: false
  - type: dropdown
    id: priority
    validations:
      required: true
    attributes:
      label: "Please assign the appropriate priority to this issue."
      description: "Please use the priorities critical / blocker carefully."
      options:
        - /priority normal
        - /priority critical
        - /priority blocker
  - type: markdown
    attributes:
      value: "# Issue Details"
  - type: textarea
    id: what-happened
    attributes:
      label: "What happened?"
      description: "Please describe the issue as detailed as possible."
      placeholder: "..."
    validations:
      required: true
  - type: textarea
    id: what-was-expected
    attributes:
      label: "What did you expect to happen and why?"
      description: "Please explain what you expected to happen and describe the configuration or resources that should have led to the expected behavior."
      placeholder: "..."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Please provide meaningful logs that outline the issue"
      description: "Please share any meaningful logs. If there are no relevant logs, enter n/a."
      placeholder: "..."
      render: bash
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: "How can we reproduce the issue (concisely and precisely)?"
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false
  - type: textarea
    id: troubleshooting
    attributes:
      label: "Actions taken"
      description: "Please describe what steps, if any, you've taken to understand, analyze, mitigate or isolate this issue."
      placeholder: "..."
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: "Anything else we should know?"
    validations:
      required: false
